name: geohydroai
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib-base
  - pandas
  - xdem=0.1.3
  - geoutils=0.1.14
  - rasterio
  - shapely=2.0.1
  - geopandas=0.13.2
  - fiona
  - pyproj
  - affine
  - duckdb
  - ipykernel
  - jupyterlab
