name: geohydroai
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib-base
  - pandas
  - xdem=0.1.3
  - geoutils=0.1.14
  - rasterio
  - shapely=2.0.1
  - geopandas=0.13.2
  - fiona
  - pyproj
  - affine
  - duckdb
  - plotly
  - ipykernel
  - jupyterlab
  - pip
  - pip:
    - dash>=3.1,<4                 # або просто >=3,<4
    - dash-deckgl==0.9.1.post1
    - dash-leaflet>=1.1.3            # поновити з 1.0.15
    - dash-bootstrap-components>=2.0
    - pykalman
    - terracotta
    - gunicorn
    - pydeck
