version: "3.9"
services:
  postgis:
    build: ./services/postgis
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./services/postgis/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 15

  terracotta:
    build: ./services/terracotta
    environment:
      TC_DRIVER: "file"
    volumes:
      - ./data/cogs:${COG_DATA_DIR}:ro
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 15

  api:
    build: ./services/api
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      TERRACOTTA_URL: ${TERRACOTTA_URL}
      DEFAULT_DEMS: ${DEFAULT_DEMS}
      SLOPE_LAYER: ${SLOPE_LAYER}
      HAND_LAYER: ${HAND_LAYER}
    depends_on:
      postgis:
        condition: service_healthy
      terracotta:
        condition: service_healthy
    ports:
      - "${API_PORT}:8000"

  dash:
    build: ./services/dash
    environment:
      API_URL: http://api:8000
    depends_on:
      - api
    ports:
      - "${DASH_PORT}:8050"

  nginx:
    build: ./services/nginx
    depends_on:
      - dash
      - api
      - terracotta
    ports:
      - "${NGINX_PORT}:80"

volumes:
  pgdata:
