CREATE TABLE IF NOT EXISTS icesat_points(
  id BIGSERIAL PRIMARY KEY,
  height DOUBLE PRECISION NOT NULL,
  geom GEOMETRY(POINTZ,4326) NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_icesat_geom ON icesat_points USING GIST(geom);
