-- services/postgis/init/02_icesat.sql
-- Точки ICESat-2 з parquet (лише колонки, які використовує дашборд).
-- Init-скрипти виконуються тільки на порожньому томі; для живої бази:
--   docker compose exec -T postgis psql -U $POSTGRES_USER -d $POSTGRES_DB < services/postgis/init/02_icesat.sql
-- Дані завантажує services/api/scripts/load_icesat.py, він же створює індекси після COPY.
-- усі точки (tracks_3857_1.parquet)
DROP TABLE IF EXISTS icesat_points;
CREATE TABLE icesat_points (
  id bigserial PRIMARY KEY,
  track double precision,
  rgt double precision,
  spot double precision,
  cycle double precision,
  time timestamp,
  year integer,
  atl03_cnf double precision,
  atl08_class double precision,
  height double precision,
  orthometric_height double precision,
  x double precision,
  y double precision,
  lulc_class double precision,
  lulc_name text,
  h_alos_dem double precision,
  delta_alos_dem double precision,
  abs_delta_alos_dem double precision,
  alos_dem_slope double precision,
  alos_dem_2000 double precision,
  alos_dem_landform text,
  alos_dem_geomorphon double precision,
  h_aster_dem double precision,
  delta_aster_dem double precision,
  abs_delta_aster_dem double precision,
  aster_dem_slope double precision,
  aster_dem_2000 double precision,
  aster_dem_landform text,
  aster_dem_geomorphon double precision,
  h_copernicus_dem double precision,
  delta_copernicus_dem double precision,
  abs_delta_copernicus_dem double precision,
  copernicus_dem_slope double precision,
  copernicus_dem_2000 double precision,
  copernicus_dem_landform text,
  copernicus_dem_geomorphon double precision,
  h_fab_dem double precision,
  delta_fab_dem double precision,
  abs_delta_fab_dem double precision,
  fab_dem_slope double precision,
  fab_dem_2000 double precision,
  fab_dem_landform text,
  fab_dem_geomorphon double precision,
  h_nasa_dem double precision,
  delta_nasa_dem double precision,
  abs_delta_nasa_dem double precision,
  nasa_dem_slope double precision,
  nasa_dem_2000 double precision,
  nasa_dem_landform text,
  nasa_dem_geomorphon double precision,
  h_srtm_dem double precision,
  delta_srtm_dem double precision,
  abs_delta_srtm_dem double precision,
  srtm_dem_slope double precision,
  srtm_dem_2000 double precision,
  srtm_dem_landform text,
  srtm_dem_geomorphon double precision,
  h_tan_dem double precision,
  delta_tan_dem double precision,
  abs_delta_tan_dem double precision,
  tan_dem_slope double precision,
  tan_dem_2000 double precision,
  tan_dem_landform text,
  tan_dem_geomorphon double precision,
  geom geometry(Point,4326) GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(x, y), 4326)) STORED
);

-- atl03_cnf=4 AND atl08_class=1 + nmad_* (NMAD_dem.parquet)
DROP TABLE IF EXISTS icesat_nmad;
CREATE TABLE icesat_nmad (
  id bigserial PRIMARY KEY,
  track double precision,
  rgt double precision,
  spot double precision,
  cycle double precision,
  time timestamp,
  year integer,
  atl03_cnf double precision,
  atl08_class double precision,
  height double precision,
  orthometric_height double precision,
  x double precision,
  y double precision,
  lulc_class double precision,
  lulc_name text,
  h_alos_dem double precision,
  delta_alos_dem double precision,
  abs_delta_alos_dem double precision,
  alos_dem_slope double precision,
  alos_dem_2000 double precision,
  alos_dem_landform text,
  alos_dem_geomorphon double precision,
  h_aster_dem double precision,
  delta_aster_dem double precision,
  abs_delta_aster_dem double precision,
  aster_dem_slope double precision,
  aster_dem_2000 double precision,
  aster_dem_landform text,
  aster_dem_geomorphon double precision,
  h_copernicus_dem double precision,
  delta_copernicus_dem double precision,
  abs_delta_copernicus_dem double precision,
  copernicus_dem_slope double precision,
  copernicus_dem_2000 double precision,
  copernicus_dem_landform text,
  copernicus_dem_geomorphon double precision,
  h_fab_dem double precision,
  delta_fab_dem double precision,
  abs_delta_fab_dem double precision,
  fab_dem_slope double precision,
  fab_dem_2000 double precision,
  fab_dem_landform text,
  fab_dem_geomorphon double precision,
  h_nasa_dem double precision,
  delta_nasa_dem double precision,
  abs_delta_nasa_dem double precision,
  nasa_dem_slope double precision,
  nasa_dem_2000 double precision,
  nasa_dem_landform text,
  nasa_dem_geomorphon double precision,
  h_srtm_dem double precision,
  delta_srtm_dem double precision,
  abs_delta_srtm_dem double precision,
  srtm_dem_slope double precision,
  srtm_dem_2000 double precision,
  srtm_dem_landform text,
  srtm_dem_geomorphon double precision,
  h_tan_dem double precision,
  delta_tan_dem double precision,
  abs_delta_tan_dem double precision,
  tan_dem_slope double precision,
  tan_dem_2000 double precision,
  tan_dem_landform text,
  tan_dem_geomorphon double precision,
  nmad_alos double precision,
  nmad_aster double precision,
  nmad_cop double precision,
  nmad_fab double precision,
  nmad_nasa double precision,
  nmad_srtm double precision,
  nmad_tan double precision,
  geom geometry(Point,4326) GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(x, y), 4326)) STORED
);
