name: Deploy (self-hosted)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug workspace
        run: |
          pwd
          ls -la
          ls -la infrastructure || true

      - name: Deploy with Docker Compose
        working-directory: ${{ github.workspace }}   # корінь твого репо на раннері
        run: |
          set -e
          ls -la
          # якщо compose в корені репо:
          docker compose -f docker-compose.yml pull || true
          docker compose -f docker-compose.yml up -d --build
          docker image prune -f || true

