name: Deploy (self-hosted)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    # Під ці лейбли підбирається твій раннер
    runs-on: [self-hosted, Linux, X64]

    steps:
      # Клонує код у робочу теку раннера
      - name: Checkout repo
        uses: actions/checkout@v4

      # Логування версії Docker (для діагностики)
      - name: Show Docker info
        run: |
          docker --version
          docker compose version || true

      # Запускаємо/перезапускаємо сервіси
      # Виконується у корені репозиторію, який чекнув раннер
      - name: Deploy with Docker Compose
        working-directory: ${{ github.workspace }}
        run: |
          set -e
          # якщо потрібні секрети/ENV — створюй тут .env або використовуй secrets
          docker compose pull || true
          docker compose up -d --build
          docker image prune -f || true
