name: Deploy to EC2 via SSH

on:
  push:
    branches: [ "main" ]  # зміни, якщо треба інша гілка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        env:
          APP_DIR: /home/ubuntu/geoai      
          BRANCH: main                     
        with:
          host: ${{ secrets.SSH_HOST }}    
          username: ${{ secrets.SSH_USER }}# ubuntu
          key: ${{ secrets.SSH_KEY }}      
          port: 22
          script: |
            set -e
            cd "$APP_DIR"
            git fetch --all
            git checkout "$BRANCH"
            git pull --rebase origin "$BRANCH"
            # якщо збираєш локально на сервері:
            docker compose pull || true
            docker compose up -d --build
            docker image prune -f || true
